services:
  pgsqldb:
    container_name: demo-ai-gent-pgsqldb
    image: postgres:14.3
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: postgre
    ports:
      - 5432:5432
    volumes:
      - pgsqldata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: demo-ai-agent-redis
    ports:
      - 6379:6379
    command: redis-server --requirepass redis_pwd

volumes:
  pgsqldata:
